### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by MacKP** [menatwork-ia/slideItMoo#14]
Es wäre sehr schön, wenn sich die Breite bei flexieblen Seiten dynamisch anpassen würde. Ich schätze mal, das dafür das JavaScript die Berechnung vornehmen sollte ^^

Viele Grüße

**Comment by kahl-dev** [comment]
Wir haben eine Option integriert mit der man die Inlinestyles skippen kann damit der Slider Responsive mit media querys aufgebaut werden kann. Das sollte auch dein Problem lösen.
