### ISSUE TITLE
Slider springt unter Chrome 21.0 hin und her

### ISSUE THREAD

**Issue by poldixd** [menatwork-ia/slideItMoo#31]
Hallo,

ich habe es jetzt bei zwei unterschiedlichen Rechnern mit Chrome 21.0 den Slider getestet. 

Wenn ich denn Slider mit AutoPlay auf die bsp. 3. Position laufen lasse, und dann über die Bulletlist auf die 2. Position klicke, springt der Slider auf die Position. Danach springt er wieder auf die 3. Position, nach der eingestellten Zeit. Jetzt läuft der Slider aber rückwärts. Er springt auf Position 2. und danach wieder auf die 3. Position.

Die Contao (2.11.3) Version ist nackig: http://contao.poltmann.com/

Mit der neusten 2.11.5 gehts auch nicht.

Erweiterungen sind wie folgt installiert:

```
changelanguage  2.0.3 stable    7   
MultiColumnWizard   3.0.0 rc1   8   
slideItMoo                  2.1.1 stable    2   
slideItMooFramework 1.0.0 stable    8
```

Jemand eine Idee?

**Comment by kahl-dev** [comment]
Der Bug wurde hier behoben:
https://github.com/menatwork/slideItMooFramework/commit/fead2b5f9cc10a51cc5cc1abcc7247ed8df07d9a

**Comment by poldixd** [comment]
Super! Danke :)
