### ISSUE TITLE
parseBackendTemplate geht schief bei leerer localconfig.php

### ISSUE THREAD

**Issue by BugBuster1701** [menatwork-ia/slideItMoo#32]
Grad im Forum gefunden, ich habe das Problem bei einer meiner Erweiterungen auch schon gehabt.

Ein Nutzer hat ein Problem und löscht die localconfig.php um per install.php alle Daten neu einzutragen.
Das geht nicht, weil slideItMoo per Hook ein Datenbankverbindung aufbauen will.
Das sieht dann so aus:

```
Fatal error: Uncaught exception Exception with message Could not connect to database (Access denied for user 'xxxx'@'localhost' (using password: NO)) thrown in /var/www/xxxx/html/cms/system/libraries/Database.php on line 78
#0 /var/www/web41/html/cms/system/libraries/Database.php(135): Database->__construct()
#1 [internal function]: Database::getInstance()
#2 /var/www/web41/html/cms/system/libraries/System.php(176): call_user_func(Array)
#3 /var/www/web41/html/cms/system/modules/backend/Backend.php(49): System->import('Database')
#4 /var/www/web41/html/cms/system/modules/slideitmoo/slideItHelper.php(53): Backend->__construct()
#5 /var/www/web41/html/cms/system/modules/slideitmoo/slideItHelper.php(73): slideItHelper->__construct()
#6 [internal function]: slideItHelper::getInstance()
#7 /var/www/web41/html/cms/system/libraries/System.php(176): call_user_func(Array)
#8 /var/www/web41/html/cms/system/modules/backend/BackendTemplate.php(56): System->import('slideItHelper')
#9 /var/www/web41/html/cms/system/modules/backend/BackendTemplate.php(144): BackendTemplate->parse()
#10 /var/www/web41/html/cms/contao/install.php(951): BackendTemplate->output()
#11 /var/www/web41/html/cms/contao/install.php(231): InstallTool->outputAndExit()
#12 /var/www/web41/html/cms/contao/install.php(961): InstallTool->run()
#13 {main}
```

Da in Contao 2 ja die localconfig.php bereits eingelesen ist (sofern vorhanden), könnte man in der getInstance ja prüfen ob `$GLOBALS['TL_CONFIG']['dbUser'] != ''` ist.
Wenn nicht, dann nicht die Instanz bilden.
Vielleicht habt Ihr ja noch ne andere Idee wie man das abfangen könnte.

**Comment by kahl-dev** [comment]
Ich wollte grad diesen Bug fixen kann aber leider die Exception nicht reproduzieren.
Wenn ich die localconf.php lösche, bekomme ich folgende Exception:

``` php
Fatal error: Uncaught exception Exception with message Could not connect to database (Access denied for user 'www-data'@'localhost' (using password: NO)) thrown in /var/www/entwicklung/_patrickkahl/2.11.3/system/libraries/Database.php on line 78

#0 /var/www/entwicklung/_patrickkahl/2.11.3/system/libraries/Database.php(135): Database->__construct()
#1 [internal function]: Database::getInstance()
#2 /var/www/entwicklung/_patrickkahl/2.11.3/system/libraries/System.php(170): call_user_func(Array)
#3 /var/www/entwicklung/_patrickkahl/2.11.3/system/modules/frontend/Frontend.php(68): System->import('Database')
#4 /var/www/entwicklung/_patrickkahl/2.11.3/system/libraries/System.php(170): Frontend->__construct()
#5 /var/www/entwicklung/_patrickkahl/2.11.3/system/libraries/Template.php(239): System->import('TemplateSelecti...')
#6 /var/www/entwicklung/_patrickkahl/2.11.3/system/modules/backend/BackendTemplate.php(49): Template->parse()
#7 /var/www/entwicklung/_patrickkahl/2.11.3/system/modules/backend/BackendTemplate.php(144): BackendTemplate->parse()
#8 /var/www/entwicklung/_patrickkahl/2.11.3/contao/install.php(951): BackendTemplate->output()
#9 /var/www/entwicklung/_patrickkahl/2.11.3/contao/install.php(231): InstallTool->outputAndExit()
#10 /var/www/entwicklung/_patrickkahl/2.11.3/contao/install.php(961): InstallTool->run()
#11 {main}
```

**Comment by BugBuster1701** [comment]
Ist hier genau dasselbe, nur hier wird es aus der Erweiterung TemplateSelection angestossen.
der nutzt zwar `$GLOBALS['TL_HOOKS']['parseTemplate']` , bringt aber genau dasselbe Problem.

**Comment by andreasisaak** [comment]
Aber wie simulierst du den Fehler?

**Comment by BugBuster1701** [comment]
Steht doch da, in einer laufenden Seite einfach mal die localconfig löschen und install.php aufrufen.
(oder Frontend, je nach Hook, bei mir gings ebend um den parseBackendTemplate Hook.)

**Comment by kahl-dev** [comment]
So hab das so implementiert. Kannst du das bitte testen denn ich kann das immer noch nicht reproduzieren, selbst wenn ich alle anderen Erweiterungen kicke.

**Comment by BugBuster1701** [comment]
sobald ich zu Hause bin teste ich das mal.

**Comment by andreasisaak** [comment]
@BugBuster1701 Ich hab deinen Beitrag schon sehr genau gelesene aber weder Patrick noch ich können das reproduzieren.

**Comment by BugBuster1701** [comment]
Also der Patch, mal abgesehen davon das er einen Syntaxfehler enthält, funktioniert so nicht. Kann wieder wech.
Interessanterweise kann ich mit der aktuellen Version von slideItMoo das auch nicht reproduzieren.  (in meinem eigenem Modul schon)
Wie im meinem erstem Post ja zu sehen ist, kommt im `slideItHelper->__construct` ja durch die parent Aufrufe zum DB Import der dann schief geht. Das scheint in der 2.11.6 nicht mehr der Fall zu sein.
Ich kann mich erinnern, das in einer der älteren Version von Contao es einen DB Import Fehler gab und der dort beseitigt wurde.
Mal sehen ob ich den Forum Thread finde, dann werd ich mal nachfragen welche Version derjenige dort hat.

**Comment by BugBuster1701** [comment]
Hier der Forum Thread https://www.contao-community.de/showthread.php?34414-InstallTool-l%E4sst-sich-nicht-zur%FCcksetzen&p=228605&viewfull=1#post228605
